#!/bin/bash

# Copyright (C) 2017-2019 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
  [-p|--prefix] \$prefix        sets the \${pkgdir} used for AUR PKGBUILD
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

# Parse arguments.
pkgdir=
while (( ${#} > 0 )); do
  case "${1}" in
  # [-p|--prefix] \$prefix        sets the \${pkgdir} used for AUR PKGBUILD
  '-p'|'--prefix') shift && pkgdir="${1}";;
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1;;
  esac; shift
done

#------------------------------------------------------------------------------#

pushd "${SCRIPT_PATH}" > /dev/null
{
  diff './fetch-radio-romania-actualitati-podcasts' "${pkgdir}/usr/local/bin"
  diff './fetch-radio-romania-actualitati-podcasts.service' "${pkgdir}/lib/systemd/system"
  diff './caddy.service' "${pkgdir}/lib/systemd/system"
  diff './Caddyfile' '/etc/caddy/Caddyfile'
  diff './podcasts-Caddyfile' '/etc/fetch-radio-romania-actualitati-podcasts/Caddyfile'
}
popd 1> /dev/null
