#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
\$mp3_index                    index of the mp3 audio files to start retrieving from
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/spinner"

# Parse arguments.
while (( ${#} > 0 )); do
  case "${1}" in
  *)
    # \$mp3_index                    index of the mp3 audio files to start retrieving from
    [[ -z "${mp3_index+x}" ]] && mp3_index=${1} && shift && continue
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1 ;;
  esac; shift
done

#------------------------------------------------------------------------------#

directory='/usr/share/o-vorba-buna'

if [[ ! -e "${directory}" ]]; then
  mkdir -p "${directory}"
fi

editions=$(curl -s http://www.romania-actualitati.ro/Podcast/o_vorba_buna/14 | pup 'div.podcastilisting a text{}')
urls=$(curl -s http://www.romania-actualitati.ro/Podcast/o_vorba_buna/14 | pup 'div.podcastilisting a attr{href}' | grep -v '#')

SAVEIFS="${IFS}"
IFS=$'\n'

editions=( ${editions} )

urls=( ${urls} )

IFS="${SAVEIFS}"

months=
i=$(( ${#urls[@]} - 1 ))
while (( i >= 0 )); do
  month="$(printf '%s' "${editions[${i}]}" | xargs | cut -d ' ' -f 4)"
  year="$(printf '%s' "${editions[${i}]}" | xargs | cut -d ' ' -f 5)"
  start-spinner "${editions[${i}]}"
  if wget -O "${directory}/0.mp3" "${urls[${i}]}" &> /dev/null; then
    month_directory="${directory}/${year}/${month}"
    mkdir -p "${month_directory}"
    filename="$(printf '%s' "${editions[${i}]}" | xargs).mp3"
    cp -p "${directory}/0.mp3" "${directory}/${filename}"
    cp -p "${directory}/0.mp3" "${month_directory}/${filename}"
    rm "${directory}/0.mp3"
  fi
  if ! [[ "${months}" = *"${month}"* ]]; then
    months="${months} ${month}"
  fi
  i=$(( i - 1 ))
  stop-spinner 0
done

arguments=()
for month in ${months}; do
  arguments+=( -not -name "*${month}*" )
done
find "${directory}" -maxdepth 1 -type f ${arguments[@]} -delete
