#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
  [-p|--prefix] \$prefix        sets the \${pkgdir} used for AUR PKGBUILD
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

# Parse arguments.
pkgdir=
while (( ${#} > 0 )); do
  case "${1}" in
  # [-p|--prefix] \$prefix        sets the \${pkgdir} used for AUR PKGBUILD
  '-p'|'--prefix') shift && pkgdir="${1}";;
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1;;
  esac; shift
done

#------------------------------------------------------------------------------#

pushd "${SCRIPT_PATH}" > /dev/null
{
  for dependency in curl gohttpserver pup wget; do
    if ! command -v ${dependency} &> /dev/null; then
      printf 'Please install %s before continuing.\n' "${dependency}" >&2
      exit 1
    fi
  done

  install './fetch-o-vorba-buna' "${pkgdir}/usr/local/bin"
  install './fetch-o-vorba-buna.service' "${pkgdir}/lib/systemd/system"
  install './gohttpserver/gohttpserver.service' "${pkgdir}/lib/systemd/system"
  if [[ ! -e '/usr/share/html/o-vorba-buna' ]]; then ln -s '/usr/share/o-vorba-buna' '/usr/share/html/o-vorba-buna'; fi
  install -d './lib' "${pkgdir}/usr/local/bin/lib"
  mkdir -p '/etc/fetch-o-vorba-buna/gohttpserver'
  cp -rf ./gohttpserver/* '/etc/fetch-o-vorba-buna/gohttpserver'
  install ./lib/* "${pkgdir}/usr/local/bin/lib"
  systemctl daemon-reload
  systemctl enable fetch-o-vorba-buna.service
  systemctl restart fetch-o-vorba-buna.service
  systemctl enable gohttpserver.service
  systemctl restart gohttpserver.service
}
popd 1> /dev/null
